apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-czlfnkxy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-czlfnkxy:164382c64410cc8a08814203c4350d729c1a8426@sha256:26146cf9ff8bd0206e5e858a285b05a42949441f5576764a8b75f0d252e64b1a
          name: container-image
